spring:
  application:
    name: sistema-facturacion-back
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sis_facturacion?createDatabaseIfNotExist=true
    username: root
    password: freddy17

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

#logging:
#  level:
#    ROOT: DEBUG